### ISSUE TITLE
Does this really use GPU?

### ISSUE THREAD

**Issue by fleek** [voun7/VidSubX#8]
I tried this and it is not using GPU?  Do we need to install paddlepaddle-GPU instead of the paddlepaddle in requirements.txt?

**Comment by voun7** [comment]
In the past, just installing paddlepaddle-GPU with conda might have worked. Now, onnx is used by default. Installing onnxruntime with conda might work. I have yet to test this. I will look further into this.

**Comment by fleek** [comment]
I have spent many hours resolving this, maybe I can help you a little bit.

1)  remove onnxruntime and install onnxruntime with versions below 1.20, the latest is 1.19.2.

2) install Cudnn and Cuda, 1.19.2 supports cuda 12.x and Cudnn 9.x

I am still getting some warnings but it is running on GPU now.  Thank you very much for this effort, I really like this program a lot. 

I am looking at using FFmeg to split the frames, rather than using opencv. opencv is too slow.

I am also looking at masking, because especially for Chinese traditional the words are pretty complex.

**Comment by voun7** [comment]
Turns out, the latest version of onnxruntime-gpu that was released on Mar 7, 2025 allows the installation of CUDA and cuDNN runtime DLLs alongside the package, no more need for Conda. I'm trying to implement them.

**Comment by fleek** [comment]
if you are talking about pip install onnxruntime[cuda,cudnn] I tried that
and lead to a lot of errors, I don't know how to fix them perhaps you can.

**Comment by voun7** [comment]
I just pushed a commit that should allow the onnxruntime-gpu[cuda,cudnn] package to use the GPU without any errors. However, I failed to see any huge performance gains from using the GPU on my computer. My guess is that I might have to tinker with the number of Onnx Intra Threads and OCR Max Processes to find what works for my computer.

**Comment by voun7** [comment]
@hieu168 GPU can be used by running `pip install onnxruntime-gpu[cuda,cudnn]==1.21.0`. `onnxruntime` should not be installed. This is what works for me, but I can't guarantee that it will work for every computer. I am yet to figure out how to make the GPU work for the program when compiled.

**Comment by hieu168** [comment]
I tried running it on GPU but it still doesn't work. Can you make a GPU version, or guide me how to compile it correctly? The program is very good, but running on CPU takes too long and can quickly damage the computer.

**Comment by voun7** [comment]
@fleek & @hieu168 a GPU version has been added to the v.1.4 release. Try it and see if it works for you.
